# -*- coding: utf-8 -*-

# C 段的原始文件输入列名
ETA_C_COLUMNS_LIST = [
    'order_id',
    'supplier_id',
    'transporter_id',
    'receiver_id',
    's_r_line_distance',
    'finish_time',
    'receiver_address',
    'cargo_type_id',
    'cargo_weight',
    'r_lng',
    'r_lat',
    'poi_id',
    'poi_lat',
    'poi_lng',
    'is_hard_poi',
    'difficulty',
    'receiver_poi_distance',
    'percentile_delivery_time_poi',
    'avg_delivery_time_poi',
    'percentile_distance_poi',
    'std_distance_poi',
    'std_delivery_time_poi',
    'order_cnt',
    'city_id',
    'delivery_time1',
    'delivery_time2',
    'error1',
    'error2',
    't_history_order_num',
    't_avg_a1_time',
    't_avg_a2_time',
    'delivery_cnt',
    'avg_delivery_time2',
    'per_delivery_time2',
    'cnt_peek1',
    'cnt_peek2',
    'cnt_peek3',
    'cnt_peek0',
    'per_delivery_time_peek1',
    'per_delivery_time_peek2',
    'per_delivery_time_peek3',
    'per_delivery_time_peek0',
]

ETA_C_COLUMNS_DICT = dict(zip(
    ETA_C_COLUMNS_LIST,
    [i for i in range(len(ETA_C_COLUMNS_LIST))]
))
