CREATE TABLE `algo_transporter_delivery_peek_Info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'auto increment id',
  `transporter_id` bigint(20) NOT NULL DEFAULT '-1' COMMENT '骑手id',
  `city_id` int(11) NOT NULL DEFAULT '0' COMMENT '城市ID',
  `delivery_cnt` int(11) NOT NULL DEFAULT '-1' COMMENT '骑手交付订单数目',
  `avg_delivery_time1` int(11) NOT NULL DEFAULT '-1' COMMENT '进圈到finish的平均时间',
  `avg_delivery_time2` int(11) NOT NULL DEFAULT '-1' COMMENT '进圈第一条到最后一条上报的平均时间',
  `per_delivery_time1` int(11) NOT NULL DEFAULT '-1' COMMENT '进圈到finish的中位数时间',
  `per_delivery_time2` int(11) NOT NULL DEFAULT '-1' COMMENT '进圈第一条到最后一条上报的中位数时间',
  `cnt_peek1` int(11) NOT NULL DEFAULT '-1' COMMENT '统计高峰阶段的订单量, 主要是午餐晚餐饭点时间',
  `cnt_peek2` int(11) NOT NULL DEFAULT '-1' COMMENT '统计高峰之间的闲时阶段的订单量',
  `cnt_peek3` int(11) NOT NULL DEFAULT '-1' COMMENT '统计半夜到清晨阶段的订单量',
  `cnt_peek0` int(11) NOT NULL DEFAULT '-1' COMMENT '统计其他阶段的订单量',
  `per_delivery_time1_peek1` int(11) NOT NULL DEFAULT '-1' COMMENT '统计高峰阶段的中位数时间, 主要是午餐晚餐饭点时间',
  `per_delivery_time1_peek2` int(11) NOT NULL DEFAULT '-1' COMMENT '统计高峰之间的闲时阶段的中位数时间',
  `per_delivery_time1_peek3` int(11) NOT NULL DEFAULT '-1' COMMENT '统计半夜到清晨阶段的中位数时间',
  `per_delivery_time1_peek0` int(11) NOT NULL DEFAULT '-1' COMMENT '统计其他阶段的订单量',
  `per_delivery_time_peek1` int(11) NOT NULL DEFAULT '-1' COMMENT '统计高峰阶段的avg时间, 主要是午餐晚餐饭点时间',
  `per_delivery_time_peek2` int(11) NOT NULL DEFAULT '-1' COMMENT '统计高峰之间的闲时阶段的avg时间',
  `per_delivery_time_peek3` int(11) NOT NULL DEFAULT '-1' COMMENT '统计半夜到清晨阶段的平均时间',
  `per_delivery_time_peek0` int(11) NOT NULL DEFAULT '-1' COMMENT '统计其他阶段的订单量',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_transporter_id_city_id` (`transporter_id`,`city_id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COMMENT='骑手的高峰低谷交付信息表';